### ISSUE TITLE
Fine Adjustment setting does nothing

### ISSUE THREAD

**Issue by OffifialMITX** [billthefarmer/sig-gen#10]
There are some buttons which I assume have a connection to the setting but the setting doesn't change anything and no matter what I chose, it turns out deactivated if I return to the main screen and go back to the settings.

**Comment by billthefarmer** [comment]
That's by design. your phone must be small enough that the fine adjustment buttons would overlap the mute button. See #5, #7. I probably ought to take the setting out of the options.
