### ISSUE TITLE
Detected as malware

### ISSUE THREAD

**Issue by Gladuin** [billthefarmer/sig-gen#12]
Malwarebytes Anti-Malware detects this app as a Trojan.BankBot.rn

**Comment by billthefarmer** [comment]
I assume you mean the latest version. I just checked it on [virustotal](https://www.virustotal.com/en/file/55493247d55cdf0e2b16c248a124550119cd6a9e2a908d4a8c398c8f83705667/analysis/1514221088/). Must be a false positive.
