### ISSUE TITLE
Awesome frequency range feature lost after upgrade

### ISSUE THREAD

**Issue by whatmusicreallyis** [billthefarmer/sig-gen#14]
Hi Bill,

Congratulations for this excellent app! It's the only one I could find that changes pitch in real time; also logarithmically, and without artifacts.

One awesome accidental feature that worked up til version 1.06 was the possibility to extend the frequency range beyond the limits of the rotary knob by using the left and right arrow buttons above it.  

This was very useful for temporal and rhythmic applications by using the squ and saw tones which click like a metronome at very low frequencies. Also excellent for hearing the transition between the temporal and spectral characteristics of sound. Unfortunately, this feature was lost (or fixed) after version 1.06.

How about extending the frequency range down to around 1 BPM = 0,01667 Hz, the slowest tempo which, according to some, can hold human attention? Maybe make this into an option in the Settings menu which will activate both the frequency knob and arrow buttons?

Thank you in advance!
Bo C-sen

**Comment by billthefarmer** [comment]
Ok, I've reduced the low limit to 0.1Hz, which is 6bpm. I play music for Morris dancing and the slowest you can play that and still be danceable is about 45bpm, which appears to be near the low limit for mechanical metronomes. It is in the current version which should appear on F-Droid some time soon.

**Comment by whatmusicreallyis** [comment]
Wonderful! Thank you for the swiftness!
