### ISSUE TITLE
can not gen square

### ISSUE THREAD

**Issue by smile-ttxp** [billthefarmer/sig-gen#16]
I need gen 270Hz square wave. i define waveform = 1 and frequency = 270.0, but it play bad wave. Where did I make a mistake?
[MyApplication.zip](https://github.com/billthefarmer/sig-gen/files/1799390/MyApplication.zip)

**Comment by billthefarmer** [comment]
That should work. It all depends how you are measuring. It you are feeding the audio output straight into an oscilloscope you might get something that looks like a square wave, depending on the audio system in the phone. If you are using a microphone held near the phone you almost certainly won't, depending on the speaker in the phone, the microphone and both audio systems.

For example, this is what I get feeding the output of the signal generator straight into the scope on Windows.
![untitled](https://user-images.githubusercontent.com/3448386/37243387-4078887c-2470-11e8-9947-d5e9d5a41298.png)
Notice the ringing. And that's just the windows audio system in the loop.

**Comment by 1989David** [comment]
I also met with such a problem. It is a fixed frequency of square wave, playing on the phone. According to your project, I extract the code. 

As follows:

 protected class Audio implements Runnable
    {
        protected static final int SINE = 0;
        protected static final int SQUARE = 1;
        protected static final int SAWTOOTH = 2;

        protected int waveform ;
        protected boolean mute;

        protected double frequency;
        protected double level;

        protected Thread thread;

        private AudioTrack audioTrack;

        protected Audio()
        {
            frequency = 270.0;
            level = 16384;
        }

        // Start
        protected void start()
        {
            thread = new Thread(this, "Audio");
            thread.start();
        }

        // Stop
        protected void stop()
        {
            Thread t = thread;
            thread = null;

            // Wait for the thread to exit
            while (t != null && t.isAlive())
                Thread.yield();
        }

        public void run()
        {
            processAudio();
        }

        // Process audio
        protected void processAudio()
        {
            short buffer[];

            int rate =
                    AudioTrack.getNativeOutputSampleRate(AudioManager.STREAM_MUSIC);
            int minSize =
                    AudioTrack.getMinBufferSize(rate, AudioFormat.CHANNEL_OUT_MONO,
                            AudioFormat.ENCODING_PCM_16BIT);

            // Find a suitable buffer size
            int sizes[] = {1024, 2048, 4096, 8192, 16384, 32768};
            int size = 0;

            for (int s : sizes)
            {
                if (s > minSize)
                {
                    size = s;
                    break;
                }
            }

            final double K = 2.0 * Math.PI / rate;

            // Create the audio track
            audioTrack = new AudioTrack(AudioManager.STREAM_MUSIC, rate,
                    AudioFormat.CHANNEL_OUT_MONO,
                    AudioFormat.ENCODING_PCM_16BIT,
                    size, AudioTrack.MODE_STREAM);
            // Check audiotrack
            if (audioTrack == null)
                return;

            // Check state
            int state = audioTrack.getState();

            if (state != AudioTrack.STATE_INITIALIZED)
            {
                audioTrack.release();
                return;
            }

            audioTrack.play();

            // Create the buffer
            buffer = new short[size];

            // Initialise the generator variables
            double f = frequency;
            double l = 0.0;
            double q = 0.0;

            while (thread != null)
            {
                // Fill the current buffer
                for (int i = 0; i < buffer.length; i++)
                {
                    f += (frequency - f) / 4096.0;
                     l += ((mute ? 0.0 : level) * 16384.0 - l) / 4096.0;
                     q += (q < Math.PI) ? f * K : (f * K) - (2.0 * Math.PI);

                   switch (waveform)
                    {
                        case SINE:
                            buffer[i] = (short) Math.round(Math.sin(q) * l);
                            break;

                        case SQUARE:
                            buffer[i] = (short) ((q > 0.0) ? l : -l);
                        break;

                        case SAWTOOTH:
                            buffer[i] = (short) Math.round((q / Math.PI) * l);
                            break;
                    }
                }

                audioTrack.write(buffer, 0, buffer.length);
            }

            audioTrack.stop();
            audioTrack.release();
        }
    }




# Direct calls in the _**project：**_
 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
       
                audio = new Audio();
                audio.start();
                if (audio != null)
                    audio.waveform = Audio.SQUARE;
            }
        }
The sound of the play is not like the sound of square wave. I don't know where there's a mistake.
And the sound of the play is not always there, and it stops for a moment.

**Comment by billthefarmer** [comment]
As I said above, the changes of getting anything like a square wave out of a phone speaker are remote.

**Comment by 1989David** [comment]
I don't want the change of square wave. But your project can be adjusted to a fixed 270HZ square wave

**Comment by billthefarmer** [comment]
Set the level to 1.0 and it works.
