### ISSUE TITLE
Android phone play fixed frequency of square wave

### ISSUE THREAD

**Issue by ChloeDimen** [billthefarmer/sig-gen#17]
Can't play square wave。It is a fixed frequency of square wave, playing on the phone. According to your project, I extract the code.

As follows:

protected class Audio implements Runnable
{
protected static final int SINE = 0;
protected static final int SQUARE = 1;
protected static final int SAWTOOTH = 2;

    protected int waveform ;
    protected boolean mute;

    protected double frequency;
    protected double level;

    protected Thread thread;

    private AudioTrack audioTrack;

    protected Audio()
    {
        frequency = 270.0;
        level = 16384;
    }

    // Start
    protected void start()
    {
        thread = new Thread(this, "Audio");
        thread.start();
    }

    // Stop
    protected void stop()
    {
        Thread t = thread;
        thread = null;

        // Wait for the thread to exit
        while (t != null && t.isAlive())
            Thread.yield();
    }

    public void run()
    {
        processAudio();
    }

    // Process audio
    protected void processAudio()
    {
        short buffer[];

        int rate =
                AudioTrack.getNativeOutputSampleRate(AudioManager.STREAM_MUSIC);
        int minSize =
                AudioTrack.getMinBufferSize(rate, AudioFormat.CHANNEL_OUT_MONO,
                        AudioFormat.ENCODING_PCM_16BIT);

        // Find a suitable buffer size
        int sizes[] = {1024, 2048, 4096, 8192, 16384, 32768};
        int size = 0;

        for (int s : sizes)
        {
            if (s > minSize)
            {
                size = s;
                break;
            }
        }

        final double K = 2.0 * Math.PI / rate;

        // Create the audio track
        audioTrack = new AudioTrack(AudioManager.STREAM_MUSIC, rate,
                AudioFormat.CHANNEL_OUT_MONO,
                AudioFormat.ENCODING_PCM_16BIT,
                size, AudioTrack.MODE_STREAM);
        // Check audiotrack
        if (audioTrack == null)
            return;

        // Check state
        int state = audioTrack.getState();

        if (state != AudioTrack.STATE_INITIALIZED)
        {
            audioTrack.release();
            return;
        }

        audioTrack.play();

        // Create the buffer
        buffer = new short[size];

        // Initialise the generator variables
        double f = frequency;
        double l = 0.0;
        double q = 0.0;

        while (thread != null)
        {
            // Fill the current buffer
            for (int i = 0; i < buffer.length; i++)
            {
                f += (frequency - f) / 4096.0;
                 l += ((mute ? 0.0 : level) * 16384.0 - l) / 4096.0;
                 q += (q < Math.PI) ? f * K : (f * K) - (2.0 * Math.PI);

               switch (waveform)
                {
                    case SINE:
                        buffer[i] = (short) Math.round(Math.sin(q) * l);
                        break;

                    case SQUARE:
                        buffer[i] = (short) ((q > 0.0) ? l : -l);
                    break;

                    case SAWTOOTH:
                        buffer[i] = (short) Math.round((q / Math.PI) * l);
                        break;
                }
            }

            audioTrack.write(buffer, 0, buffer.length);
        }

        audioTrack.stop();
        audioTrack.release();
    }
}
Direct calls in the project：

@override
protected void onCreate(Bundle savedInstanceState) {
super.onCreate(savedInstanceState);
setContentView(R.layout.activity_main);

            audio = new Audio();
            audio.start();
            if (audio != null)
                audio.waveform = Audio.SQUARE;
        }
    }
The sound of the play is not like the sound of square wave. I don't know where there's a mistake.
And the sound of the play is not always there, and it stops for a moment.

**Comment by billthefarmer** [comment]
See my comments to #16. If it stops it is probebly because the phone is busy.

**Comment by ChloeDimen** [comment]
Hi billthefarmer:
                       I can't understand what you mean. Run your mobile phone in your project and adjust the 270Hz continuous square wave. I extract it, not a continuous square wave. It's just a short sound at one end. You say it's because the phone is busy, but I don't use the phone. Just run the app project on the phone. The ultimate goal is to obtain a continuous square wave of 270Hz.

**Comment by billthefarmer** [comment]
Here is a zipped project with your code. I have changed the level to 1.0. The app was run on an emulator and the audio output looped back so it could be shown on my scope app. That looks like a square wave at about 270Hz to me.

[Square.zip](https://github.com/billthefarmer/sig-gen/files/1819257/Square.zip)

![square](https://user-images.githubusercontent.com/3448386/37522262-50531fc8-291b-11e8-9f3e-74eb0d8fab4c.png)

**Comment by ChloeDimen** [comment]
Thank you.
