### ISSUE TITLE
When display sleeps during use, it changes to 1k sine

### ISSUE THREAD

**Issue by snelltheta** [billthefarmer/sig-gen#2]
It would be nice for it to keep the screen awake instead of this happening, but it would also be nice if the app can play signal while screen is off.

Perhaps a user setting could choose the behavior.

**Comment by billthefarmer** [comment]
That's an interesting one, it happens on a Moto G, but not on a Nexus 7 or a Nexus 10. I deliberately wrote it to run in the background, I will have to experiment with preventing the device sleeping.

**Comment by billthefarmer** [comment]
I have pushed a new release with a new layout for phones and a wake lock icon in the toolbar to stop the device sleeping. It should be on F-Droid in a day or so.

**Comment by snelltheta** [comment]
The problem persists, even though there is a workaround with keeping screen awake.
When I get time, I'll try to help if possible.

**Comment by billthefarmer** [comment]
I have done some more testing, both with the app as it is, which allows the screen to dim, and with the wake lock feature changed to PARTIAL_WAKE_LOCK which allows the screen to turn off. On both a phone and a tablet with the app as is the screen stays on dim whether the app is on the screen, or some other app, or the launcher is on the screen.

If you press the power button with the launcher or some other app on the screen the screen goes off, but the signal generator app isn't reset and if you bring it back on to the screen the frequency, etc are as previously set. If the app is on the screen and you press the power button the app is reset and goes back to the default 1k sine wave.

The behaviour is the same with the app as is or with the wake lock set to allow the screen to go off, the only difference is whether the screen stays dim or goes off when you don't press the power button and just leave it.

The only way I can think of to get around this is to save the state of the app and restore it when restarted. This will mean that the app will always start up as it was left the last time it was used. I will try this and see what happens.

**Comment by billthefarmer** [comment]
I have pushed a new release with save and restore app state to work around the app being restarted in the background despite the wake lock. The app state is not preserved between separate invocations of the app.

**Comment by snelltheta** [comment]
I tried 1.04, and it works well on my device. A small bug is presented, though. The bug is that the frequency will glide from 1k of the waveform to the set frequency coming in and out of display on/off.
Minor problem there, but once that's solved, I fail to see how this app would be anything less than rock solid.

**Comment by sm4rk0** [comment]
I confirm @snelltheta's finding.

**Comment by billthefarmer** [comment]
I managed to get my tablet to do it once. I think there might sometimes be a delay while the display rotates. I have changed the restore code so it gets run immediately the app is restarted. New version should appear on F-Froid within a day or so.
