### ISSUE TITLE
phase

### ISSUE THREAD

**Issue by ulph0** [billthefarmer/sig-gen#21]
hi bill,
thanks for your signal generator. i am sorry this is more a feature request, since i din't kjnow how to contact you. i would like to play around with it a bit to try reduce my tinnitus with it. as i understand it therefore it would be necessary to change/revert the phase of the sinus signal. maybe you are interested in that. regards!

**Comment by billthefarmer** [comment]
Changing the phase of an audio signal without a reference doesn't really achieve anything, IMHO. If you have something to compare, like another signal, you can very finely adjust the frequency with the fine frequency slider or the two buttons above it to change the relative phase.

You can demonstrate this with either two phones running this app, or you can use the Windows or Mac version from [here](https://github.com/billthefarmer/audiotools/releases). Set them both to exactly the same frequency, then adjust the frequency of one so you can hear the phase changing causing a slow beat.

**Comment by ulph0** [comment]
thanks for answering bill. as far as i understood it, the reference is the sound in your head when you have a sinus-like tinnitus. you first try to match the frequency and then change the phase, which could result in reducing or lowering the tinnitus sound. but maybe i am wrong ...
