### ISSUE TITLE
check this issue

### ISSUE THREAD

**Issue by Ena73** [billthefarmer/sig-gen#23]
https://www.reddit.com/r/fdroid/comments/g7qoyp/signal_generator_apk_malware/

**Comment by billthefarmer** [comment]
All my apps are built by F-Droid on a secure build system. This has come up before &ndash; #8. Check it out with https://www.virustotal.com.

**Comment by k3b** [comment]
i just checked www.virustotal.com with this apk source: https://f-droid.org/repo/org.billthefarmer.siggen_121.apk

[It found no issues](https://www.virustotal.com/gui/url/e1b43bd929482f2b8339a6e0e54c927cc6d293f6a4cab2a66ea8ecbc19fe8c4a/detection)
