### ISSUE TITLE
the problem is in the interface

### ISSUE THREAD

**Issue by OmlineEditor** [billthefarmer/sig-gen#24]
my interface is not very nicely shown. the buttons overlap each other. the numbers are superimposed.

Signal Generator 1.22 (122) F-Droid
Andrion 9.0
Xiaomi Redmi Note 7

![bug](https://user-images.githubusercontent.com/13348933/120691936-c77b4e80-c4af-11eb-8f12-5120533d6e65.jpg)

**Comment by billthefarmer** [comment]
Well that's interesting, the calculation of half of the display width is wrong. I have made some changes that should fix that. I have attached an updated debug version of the app, if you could test it. You will have to uninstall the existing version first. If that doesn't work, if you have access to adb, you can get some useful info from the debug version by running it:
```shell
 adb logcat *:S SiggenView
--------- beginning of main
--------- beginning of system
06-04 10:54:31.667  4329  4329 D SiggenView: Dim: 0, 0
06-04 10:54:31.667  4329  4329 D SiggenView: Dim: 0, 0
06-04 10:54:31.678  4329  4329 D SiggenView: Dim: 0, 0
06-04 10:54:31.679  4329  4329 D SiggenView: Dim: 0, 0
06-04 10:54:31.702  4329  4329 D SiggenView: Dim: 1152, 544
06-04 10:54:31.703  4329  4329 D SiggenView: Dim: 1152, 544
06-04 10:54:31.704  4329  4329 D SiggenView: Dim: 1152, 544
06-04 10:54:31.705  4329  4329 D SiggenView: Dim: 1152, 544
```
[SigGen-debug.zip](https://github.com/billthefarmer/sig-gen/files/6597588/SigGen-debug.zip)

**Comment by OmlineEditor** [comment]
the new version is better. I ask you to change the code and put the new version on f-droid.
![1](https://user-images.githubusercontent.com/13348933/120838419-767f5f00-c570-11eb-97be-654b822770ee.jpg)
![2](https://user-images.githubusercontent.com/13348933/120838431-797a4f80-c570-11eb-8d16-b9c317ddec14.jpg)

**Comment by billthefarmer** [comment]
OK, that will be in the next version.
