### ISSUE TITLE
Fix frequency aliasing

### ISSUE THREAD

**Issue by mamins1376** [billthefarmer/sig-gen#26]
Attempting to play waveforms containing harmonics with frequencies above the Nyquist rate results in aliasing. The output will lose it's intended form.

To reproduce, choose a waveform other than sine, set the frequency to around 10Khz, and slowly increase it via the knob. You will will hear weird sounds being produced due to this phenomenon.

One possible solution would be to band-limit the generated waveform before handing the signal to the system, using a low pass filter.

**Comment by billthefarmer** [comment]
There are two relevant points: The output sample rate is determined by the device, so the filer cut-off frequency would be variable; A filter with a sharp enough cut-off to make an appreciable difference would cause distortion of the square and sawtooth output waveforms. I also have no idea how to go about designing such a filter.
