### ISSUE TITLE
I got a trojan warning

### ISSUE THREAD

**Issue by practice40hoursaday** [billthefarmer/sig-gen#27]
![Screenshot_20211001-040149](https://user-images.githubusercontent.com/78695261/135559597-e9f9823e-4af2-4f0d-b43b-5d004eb8aead.jpg)
I get a warning from malwarebytes that the app got recognized it as a trojan.

**Comment by billthefarmer** [comment]
This has happened before, see #12. Check it on virustotal.com.Sent from my Galaxy
-------- Original message --------From: practice40hoursaday ***@***.***> Date: 01/10/2021  04:13  (GMT+00:00) To: billthefarmer/sig-gen ***@***.***> Cc: Subscribed ***@***.***> Subject: [billthefarmer/sig-gen] I got a trojan warning (#27) 

I get a warning from malwarebytes that the app got recognized it as a trojan.

**Comment by billthefarmer** [comment]
[VirusTotal results](https://www.virustotal.com/gui/url/dc64fd229354a89c2b4a448bf14ab66c189ad3416145961adde5e071af6567fd?nocache=1).
