### ISSUE TITLE
Add option to independently set level of left and right channel

### ISSUE THREAD

**Issue by woheller69** [billthefarmer/sig-gen#29]

**Comment by billthefarmer** [comment]
It's a mono signal generator.

**Comment by woheller69** [comment]
Making it stereo should not be a big problem.

AudioFormat.CHANNEL_OUT_MONO must be changed to AudioFormat.CHANNEL_OUT_STEREO

and the buffer size needs to be doubled with alternating values for left and right channel

**Comment by billthefarmer** [comment]
AFAICT, there is no such instrument as a stereo audio signal generator &ndash; https://duckduckgo.com/?t=ffab&q=stereo+audio+signal+generator&ia=web. If you feel you really can't exist without one, please feel free to fork this app.

**Comment by woheller69** [comment]
found one with dual channel function 

http://keuwl.com/FunctionGenerator/
