### ISSUE TITLE
Tone starts playing immediately upon opening

### ISSUE THREAD

**Issue by deoxal** [billthefarmer/sig-gen#30]
It's very jarring to have the tone start playing immediately and can annoy people around. I think it should be muted by default or not play a tone until the frequency is changed.

**Comment by billthefarmer** [comment]
It's a signal generator. That's what they do.

**Comment by deoxal** [comment]
Shock the user and not let the tone and volume to be set to not disturb others? No it doesn't have to do that.

Why even have the mute? It keeps the signal generator from performing its only function when tapped.

PA Tone at least remembers if the app was closed while the tone was being played or not.

https://play.google.com/store/apps/details?id=com.dutchmatic.patone

**Comment by billthefarmer** [comment]
Why are you using a signal generator app with nothing connected to the phone if you don't want to annoy people? The expected use case is for some sort of audio testing, so the phone would be connected via the audio jack to something else.

**Comment by deoxal** [comment]
It's just fun to play with which I often do with external speakers. However I don't always connect the speakers first. The reason I made this issue though was I updated the app after a few months and opened it to see what was new and got an ear splitting tone.

**Comment by billthefarmer** [comment]
OK, that will be in the next version
