### ISSUE TITLE
Android 12 volume trouble

### ISSUE THREAD

**Issue by Bevans7070** [billthefarmer/sig-gen#35]
I have Android 12 and it works well on Android 11 but breaks up and loses volume on Android 12.
Great app.

**Comment by billthefarmer** [comment]
I have a Pixel 3a phone running android 12. The volume is a bit low, but I think this is down to the default media volume setting. Apart from that it works fine. I have an old Moto G phone which had become very laggy when running android 7 with all the google cruft installed, which is constantly being updated. When I rebuilt it without the google apps, it runs very fast, just like new. Your phone might be full of google cruft or just need a reboot.

![Screenshot_20230501-124439_Settings 1](https://user-images.githubusercontent.com/3448386/235448328-38402f75-69b5-4a98-8570-310ecf1f89da.png)

**Comment by Bevans7070** [comment]
I love the app.
I have Samsung Ao3s with Android 12.
All volume are maxed out.
The app runs normal until something in the screen brightness changes like notifications and the volume breaks up and lowers.
It does it when I key the screen off too.
I don't know the cause....Android 11 no trouble.

**Comment by Bevans7070** [comment]
I had to buy a new Samsung Ao3s to replace older one and downloaded signal
generator onto new phone but didn't use it right then.I used smart switch
app to transfer all data to new phone.
I found trouble with signal generator and uninstalled and reinstalled it
several times with the same result.
I need the app to fight my boomstupid neighbor.
Would you help me sort this out?

**Comment by billthefarmer** [comment]
I can't investigate that without going out to buy a Samsung Ao3s, which I'm not going to do. The app works fine on all the devices and emulators I have.

**Comment by Bevans7070** [comment]
I appreciate the problem with bridging the gap.
It works on my other phone so I'll keep it and delete app on new
phone(useless).
Thanks for your time and effort.
I guess Fdroid deleted my account....no access since post.
