### ISSUE TITLE
Feature request: PWM

### ISSUE THREAD

**Issue by orbiterFan** [billthefarmer/sig-gen#37]
Hi Bill

Been using your app for a while. Thanks for the dial knob interface.

Do you think you can implement pulse width modulation with adjustable duty cycle.

Typical use case to test an electric motor with a headphone jack plugging into the motor driver.

Pwm duty cycle from as close to 1% to 100% with a slider of dial, if doable.

Will keep tracking your app.

**Comment by billthefarmer** [comment]
OK, have added a slider for duty cycle and added duty to the external control. That will be in the next version.

**Comment by orbiterFan** [comment]
Look forward to trying it out. Thanks for the update.
