### ISSUE TITLE
Blank

### ISSUE THREAD

**Issue by octavo** [billthefarmer/sig-gen#38]
The app doesn't show any controls. It's blank.

![img_14.jpg](https://github.com/billthefarmer/sig-gen/assets/1730033/7f5fd564-7d8a-4a4e-9141-67158b7ef365)

**Comment by billthefarmer** [comment]
That's a good one, the app is supposed to be landscape only. It certainly won't work in portrait. What device are you using?

**Comment by octavo** [comment]
It works now on Android Samsung Galaxy XCover Pro.

7 Nov 2023 12:57:25 Bill Farmer ***@***.***>:
