### ISSUE TITLE
missing documentations

### ISSUE THREAD

**Issue by KrischnaGabriel** [billthefarmer/sig-gen#39]
## missing documentations for setting up a development environment

This will sound idiotic but I'm trying to fork this app for an custom project and I can't get it to build.

when I just open the project in a text editor of choice (vscode) intellisense and Linting does not work because
```
Main.java is not on the classpath of project sig-gen, only syntax errors are reported
```
When I try to run the gradlew.bat script I get this error:
```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```

I know of the Android Studio from Google and installed it and opened the project in it. Besides it being ridiculously cpu expensive I could not figure out how to get it build or even just error highlighting (Linting) to work. 
I'm kinda lost.
How do you build this thing?

## missing documentations for code and variables.

the `Main.java` is of most interest to me so I'll take an example from there. more specific the `processAudio` method at the very end.

`duty`, `t`, `K`, `f`, `level`, `q`, `l`
what are the number ranges for these variables?
what do they represent?
why is there so much Pi involved?
what is the purpose of these cryptic one letter variables?
if `f` stands for frequency, what does `frequency` stand for? poor naming and no meaningful comments!

If I'd design this code I'd assume I get 
* a buffersize
* a sampling rate
* audio volume level as a float ranging from 0 to 1
* the frequency as a float ranging from 0.1 to 25000
* and the duty cycle as a float ranging from 0 to 1

Then I iterate over the buffersize. using the sampling rate I can calculate the time step between each iteration and increment a global ms variable each time by that amount. that variable I then can use to calculate the waveforms.
The output audio samples are a float ranging from 0 to 1

I would greatly appreciate comments that describe the valid number range and purpose so that I don't have to reverse engineer the whole app (if I could get it to build in the first place) just to make a few tweaks.

**Comment by billthefarmer** [comment]
I build my apps using gradle and the android SDK. I don't know why you can't import it into Android Studio, others who offer pull requests have no difficulty, there are two for this app I haven't looked at yet.
```shell
-*- mode: compilation; default-directory: "d:/android/SigGen/" -*-
Compilation started at Thu Nov  9 08:38:56

gradlew build
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :preBuild UP-TO-DATE
> Task :preDebugBuild UP-TO-DATE
> Task :mergeDebugNativeDebugMetadata NO-SOURCE
> Task :compileDebugAidl NO-SOURCE
> Task :compileDebugRenderscript NO-SOURCE
> Task :generateDebugBuildConfig
> Task :javaPreCompileDebug UP-TO-DATE
> Task :checkDebugAarMetadata UP-TO-DATE
> Task :generateDebugResValues UP-TO-DATE
> Task :mapDebugSourceSetPaths UP-TO-DATE
> Task :generateDebugResources UP-TO-DATE
> Task :mergeDebugResources UP-TO-DATE
> Task :createDebugCompatibleScreenManifests
> Task :extractDeepLinksDebug UP-TO-DATE
> Task :processDebugMainManifest
> Task :processDebugManifest
> Task :mergeDebugShaders UP-TO-DATE
> Task :compileDebugShaders NO-SOURCE
> Task :generateDebugAssets UP-TO-DATE
> Task :mergeDebugAssets UP-TO-DATE
> Task :compressDebugAssets UP-TO-DATE
> Task :processDebugJavaRes NO-SOURCE
> Task :mergeDebugJavaResource UP-TO-DATE
> Task :checkDebugDuplicateClasses UP-TO-DATE
> Task :desugarDebugFileDependencies UP-TO-DATE
> Task :mergeExtDexDebug UP-TO-DATE
> Task :mergeLibDexDebug UP-TO-DATE
> Task :mergeDebugJniLibFolders UP-TO-DATE
> Task :mergeDebugNativeLibs NO-SOURCE
> Task :stripDebugDebugSymbols NO-SOURCE
> Task :validateSigningDebug UP-TO-DATE
> Task :writeDebugAppMetadata UP-TO-DATE
> Task :writeDebugSigningConfigVersions UP-TO-DATE
> Task :preReleaseBuild UP-TO-DATE
> Task :compileReleaseAidl NO-SOURCE
> Task :compileReleaseRenderscript NO-SOURCE
> Task :generateReleaseBuildConfig
> Task :javaPreCompileRelease UP-TO-DATE
> Task :checkReleaseAarMetadata UP-TO-DATE
> Task :generateReleaseResValues UP-TO-DATE
> Task :mapReleaseSourceSetPaths UP-TO-DATE
> Task :generateReleaseResources UP-TO-DATE
> Task :mergeReleaseResources UP-TO-DATE
> Task :createReleaseCompatibleScreenManifests
> Task :extractDeepLinksRelease UP-TO-DATE
> Task :processReleaseMainManifest
> Task :processReleaseManifest
> Task :extractProguardFiles UP-TO-DATE
> Task :mergeReleaseJniLibFolders UP-TO-DATE
> Task :mergeReleaseNativeLibs NO-SOURCE
> Task :stripReleaseDebugSymbols NO-SOURCE
> Task :extractReleaseNativeSymbolTables NO-SOURCE
> Task :mergeReleaseNativeDebugMetadata NO-SOURCE
> Task :checkReleaseDuplicateClasses UP-TO-DATE
> Task :desugarReleaseFileDependencies UP-TO-DATE
> Task :mergeExtDexRelease UP-TO-DATE
> Task :mergeReleaseArtProfile UP-TO-DATE
> Task :mergeReleaseShaders UP-TO-DATE
> Task :compileReleaseShaders NO-SOURCE
> Task :generateReleaseAssets UP-TO-DATE
> Task :mergeReleaseAssets UP-TO-DATE
> Task :compressReleaseAssets UP-TO-DATE
> Task :processReleaseJavaRes NO-SOURCE
> Task :mergeReleaseJavaResource UP-TO-DATE
> Task :collectReleaseDependencies UP-TO-DATE
> Task :sdkReleaseDependencyData UP-TO-DATE
> Task :writeReleaseAppMetadata UP-TO-DATE
> Task :writeReleaseSigningConfigVersions UP-TO-DATE
> Task :preDebugAndroidTestBuild SKIPPED
> Task :processDebugAndroidTestManifest UP-TO-DATE
> Task :compileDebugAndroidTestRenderscript NO-SOURCE
> Task :generateDebugAndroidTestResValues UP-TO-DATE
> Task :preDebugUnitTestBuild UP-TO-DATE
> Task :javaPreCompileDebugUnitTest UP-TO-DATE
> Task :processDebugUnitTestJavaRes NO-SOURCE
> Task :preReleaseUnitTestBuild UP-TO-DATE
> Task :javaPreCompileReleaseUnitTest UP-TO-DATE
> Task :processReleaseUnitTestJavaRes NO-SOURCE
> Task :processDebugManifestForPackage
> Task :processReleaseManifestForPackage
> Task :processReleaseResources
> Task :processDebugResources
> Task :compileDebugJavaWithJavac
> Task :dexBuilderDebug
> Task :compileReleaseJavaWithJavac
> Task :mergeProjectDexDebug
> Task :dexBuilderRelease
> Task :packageDebug
> Task :createDebugApkListingFileRedirect
> Task :assembleDebug
> Task :bundleDebugClassesToRuntimeJar
> Task :bundleDebugClassesToCompileJar
> Task :mergeDexRelease
> Task :optimizeReleaseResources
> Task :compileReleaseArtProfile
> Task :compileDebugUnitTestJavaWithJavac NO-SOURCE
> Task :testDebugUnitTest NO-SOURCE
> Task :packageRelease
> Task :createReleaseApkListingFileRedirect
> Task :bundleReleaseClassesToCompileJar
> Task :compileReleaseUnitTestJavaWithJavac NO-SOURCE
> Task :bundleReleaseClassesToRuntimeJar
> Task :testReleaseUnitTest NO-SOURCE
> Task :test UP-TO-DATE
> Task :lintVitalAnalyzeRelease
> Task :lintVitalReportRelease SKIPPED
> Task :lintVitalRelease SKIPPED
> Task :assembleRelease
> Task :assemble
> Task :lintAnalyzeDebug
> Task :lintReportDebug
> Task :lintDebug
> Task :lint
> Task :check
> Task :build

BUILD SUCCESSFUL in 33s
74 actionable tasks: 32 executed, 42 up-to-date

Compilation finished at Thu Nov  9 08:39:33
```
I don't document my apps in the level of detail you seem to expect, I am a retired geek and do this for fun. The processAudio function first finds out the device's output sample rate, then finds a suitable buffer size, Then calculates the constant K, which is the magik number for the frequency calculation. It then opens an audiotrack for output and checks that it's OK, then starts it playing. The single letter variables are used in the generator loop for generating the output data.

- K &ndash; magik constant
- f &ndash; frequency
- l &ndash; level
- q &ndash; point on the output wave
- t &ndash; point on wave where square wave changes from l to -l

Because changing frequency or level rapidly using the twirly knob or the mute button can generate horrible noises, the frequency and level are changed slowly by the code...
```java
                    f += (frequency - f) / 4096.0;
                    l += ((mute ? 0.0 : level) * 16384.0 - l) / 4096.0;
                    q += ((q + (f * K)) < Math.PI) ? f * K :
                        (f * K) - (2.0 * Math.PI);
````
The loop fills the buffer, writes it out and continues. You can't escape using pi or some other magik constant for generating sine waves.
