### ISSUE TITLE
Allow entering exact frequency with on-screen keyboard ?

### ISSUE THREAD

**Issue by strk** [billthefarmer/sig-gen#4]
I wanted to try a 440Hz but could not get there, the closer I could get was 440.05.
This is on a smartphone, so maybe with a tablet it's easier, anyway I've been hoping I could tap on the frequency indicator to enter a number with the on-screen keyboard. Just a feature request.

I love what you're making for music players, thank you !

**Comment by billthefarmer** [comment]
There are two points here. Showing the frequency to five digits of precision is probably overstating the accuracy of the underlying android audio system. It is possible to get 440.01Hz by picking 436.52Hz on the coarse knob and then adjusting the fine slider by rolling your finger on it. That works on a phone and a tablet. I will experiment with another couple of adjusting buttons like on the knob.

**Comment by billthefarmer** [comment]
Ok, that works. I will release a new version with fine adjustment buttons.

**Comment by strk** [comment]
Thanks !
