### ISSUE TITLE
ui issue 

### ISSUE THREAD

**Issue by kilroythe5th** [billthefarmer/sig-gen#5]
There's some random extra buttons 
![tmp_11106-screenshot_2017-02-24-15-20-441707892726](https://cloud.githubusercontent.com/assets/20712758/23324896/d1a8aafc-faa5-11e6-8ee9-a53138c240d0.png)

**Comment by billthefarmer** [comment]
The extra buttons are for fine adjustment of frequency. I will have to 
do a small layout, possibly without those buttons. Please let me know 
what phone you used for the screenshot.

**Comment by billthefarmer** [comment]
I have changed the layout and added an option in the settings to remove the extra buttons if they overlap.
![screenshot_1488200947](https://cloud.githubusercontent.com/assets/3448386/23362615/83e7fba6-fcee-11e6-905e-a9a4a24841fa.png)
This screenshot is from a Nexus S emulator, which appears to be similar to your phone. I will push a new version with these changes.

**Comment by kilroythe5th** [comment]
it probobly only happened on low resolution screens, then. ( mine is 480x800)

**Comment by kilroythe5th** [comment]
![tmp_2919-screenshot_2017-03-05-21-29-45-1715222679](https://cloud.githubusercontent.com/assets/20712758/23635440/b9b394e8-0284-11e7-9f5c-f4f49dc2a29a.png)
the buttons are nicely lined up now, but they are over the "mute"  button now

**Comment by billthefarmer** [comment]
It does actually work, even though the buttons overlap. Touching in the middle of the mute button mutes, and the two fine adjustment buttons work as well, and you can remove them in the settings.
