### ISSUE TITLE
Interface broken after upgrade

### ISSUE THREAD

**Issue by AntiSol** [billthefarmer/sig-gen#6]
Hi. I just upgraded to the latest version via f-droid and now the interface is broken, making the app pretty much unusable. See screenshot. I am running cyanogenmod ob a samsung galaxy S3. Let me know if there's any other relevant info you need 🙂
![screenshot_20170305-195126](https://cloud.githubusercontent.com/assets/351169/23585905/d3bb0134-01dd-11e7-947f-31666b21b057.png)

**Comment by billthefarmer** [comment]
I suggest you uninstall and delete it and check your device. Kaspersky antivirus, both on Android and on my desktop says it's infected with a virus. I don't build my apps myself, I post the versions built by F-Droid.

**Comment by AntiSol** [comment]
Sorry I'm not 100% clear what you mean by "Kaspersky antivirus, both on Android and on my desktop says it's infected with a virus. I don't build my apps myself, I post the versions built by F-Droid". 

Do you mean the apk built by f-droid is infected?

**Comment by billthefarmer** [comment]
Yes, according to Kasperky. I just downloaded it again and checked with https://www.virustotal.com. This is the results: https://www.virustotal.com/en/file/cba3a9b9d44aa994a59662337e2d7729e64526737012050d30e71afc747e00dc/analysis. In case this link doesn't work for someone else, the results were:
AegisLab 	SUSPICIOUS 	20170305
Kaspersky 	HEUR:Trojan-Banker.AndroidOS.Hqwar.san 	20170305
Rising 	Malware.Strealer/Android!8.5B3 (cloud:CiwLqU2doWQ) 	20170305 

Also the file structure of the resources in the downloaded apk is different to the sources.

**Comment by AntiSol** [comment]
Thanks. I've removed it, will scan my device, and I'll raise an issue with the f-droid people and refer them back here. Cheers.

**Comment by billthefarmer** [comment]
I think it must be a false positive. I just reverted my sources to v1.09 to check your problem and Kaspersky deleted the classes.dex file from the build. See discussion here: https://forum.f-droid.org/t/virus-signal-generator/131.

**Comment by AntiSol** [comment]
Issue raised: https://gitlab.com/fdroid/fdroiddata/issues/627
If there's any other info you think I should include let me know. 

Would you happen to know where I can get a good apk for your app?

Thanks for your help

**Comment by AntiSol** [comment]
Damn false positives.

OK, so any ideas why it's not working for me then? Any more info I can give you?

**Comment by billthefarmer** [comment]
Looking at your screenshot, your device looks like a tablet or large phone. I can't reproduce your problem on the devices I've got and the emulators I use for testing. What exactly is your device, and what version of android are you running?  You can get version 1.08 from https://github.com/billthefarmer/sig-gen/releases/tag/v1.08. The changes were only to allow the extra buttons to be removed if they overlapped.

**Comment by AntiSol** [comment]
Nope, not a tablet, it's a samsung galaxy S3 running the last cyanogenmod nightly (14.1-20161225-nightly-i9300). Android version is 7.1.1.

The older version of the app worked just fine. I'm pretty sure that was version 1.06, but I can't install that via f-droid anymore to check - it seems that the older versions are removed from their repo.

**Comment by AntiSol** [comment]
I already tried installing v1.07 from f-droid and that has the same problem. But I've now also tried the v1.08 you linked to and also see the same issue.

I also just tried rebooting the device, no difference.

**Comment by billthefarmer** [comment]
I didn't change the layout between versions 1.06 and 1.07, but I did change the build from ant to gradle. I will see if I can reproduce your problem with an emulator. F-Droid have removed old versions, but they are all still here: https://github.com/billthefarmer/sig-gen/releases, built by F-Droid.

**Comment by billthefarmer** [comment]
OK, I've got it - The method I was using for the widgets in this app to work out their size stopped working in android 7. I will post a new version when I have done some more testing. The new version will remove the extra buttons if they overlap and update the preferences.

**Comment by AntiSol** [comment]
Awesome news. I was just about to tell you I've gone right back to v1.01 and none of them work. This would explain why.

I don't need it urgently so there's no rush to get a new version out. I'm also happy to test and let you know how it turns out if that's helpful.

Thanks for your help, particularly for such a fast reply! :)

**Comment by AntiSol** [comment]
confirming that this is fixed after updating. thank you! :)
