### ISSUE TITLE
buttons covering "mute" button

### ISSUE THREAD

**Issue by kilroythe5th** [billthefarmer/sig-gen#7]
after the latest update, instead of the tuning buttons floating near the "mute" button, they now directly cover it up

**Comment by kilroythe5th** [comment]
here's a screenshot
![tmp_5450-screenshot_2017-03-05-21-29-45-1715222679](https://cloud.githubusercontent.com/assets/20712758/23635875/1165cd9e-0287-11e7-96b0-47bbee8aaa51.png)

**Comment by billthefarmer** [comment]
There is an option in the settings to remove the extra buttons if they overlap. The next version, v1.10 will remove the buttons if they overlap. Unfortunately for developers there are far too many different devices out there to get the layout exactly right for every one of them.

**Comment by kilroythe5th** [comment]
ok, cool. 
It works now, thanks!
