### ISSUE TITLE
possible virus in sig-gen

### ISSUE THREAD

**Issue by paulmcg1** [billthefarmer/sig-gen#8]
Malwarebytes 2.1.1.6 (for Android) with the latest database is reporting that Signal Generator 1.10 has a virus (see screen below). I assume that is a "false positive" but can you look into this? I downloaded Signal Generator 1.10 from f-droid.org .

![screenshot_2017-04-21-06-41-36](https://cloud.githubusercontent.com/assets/14362023/25288657/31045504-267b-11e7-8ce2-cb55d8388ae8.png)

**Comment by paulmcg1** [comment]
See this article for more information.
[https://www.helpnetsecurity.com/2017/04/18/bankbot-trojan-google-play/](url)

**Comment by billthefarmer** [comment]
This has come up before, see #6. I have retested it, the results are: https://www.virustotal.com/en/file/a3411ed7b27612e4fe465f550ef7071ac6c2bd524cee94cf9c6802a573143efd/analysis/1492796096/. These apps are built very carefully by F-Droid in a virtual machine. I think it is a false positive.

**Comment by paulmcg1** [comment]
Are you using any third-party libraries that might contain a virus?

**Comment by billthefarmer** [comment]
Not in this app. F-Droid only allows libraries from trusted sources or built as part of the app.

**Comment by paulmcg1** [comment]
Thanks for the information. I will close the issue because it's due to a "false positive" in the Android version of Malwarebytes.

**Comment by eighthave** [comment]
F-Droid requires all apps are built from 100% source.  I've never heard of a trojan or virus entering any free software distro with similar requirements (Debian, Ubuntu, Fedora, Redhat, SUSE, Gentoo, etc).

**Comment by k3b** [comment]
i just checked www.virustotal.com with this apk source: https://f-droid.org/repo/org.billthefarmer.siggen_121.apk

[It found no issues](https://www.virustotal.com/gui/url/e1b43bd929482f2b8339a6e0e54c927cc6d293f6a4cab2a66ea8ecbc19fe8c4a/detection)
