### ISSUE TITLE
Frequency bookmarks

### ISSUE THREAD

**Issue by strk** [billthefarmer/sig-gen#9]
I've been asked by trumpet teacher to buzz a target note, tuning to something.
Signal generator would be great for this, but I don't know note frequencies by heart so I thought it would be great to have "bookmarks" for easily jump to preferred frequencies.

Bookmarks would probably be the most flexible way to deal with it, so there's no enforcement of any scale of tuning..

**Comment by billthefarmer** [comment]
I will release a new version with frequency bookmarks - [README](https://github.com/billthefarmer/sig-gen/blob/master/README.md). F-Droid is currently a bit slow - they haven't released a new version of an app I released nearly a week ago.

**Comment by strk** [comment]
Wow you are my hero. Thank you !
